### ISSUE TITLE
About Closing The Queue

### ISSUE THREAD

**Issue by dhishkyaon** [Sangwan5688/BlackHole#102]
If a user is playing a big playlist and wants to change some songs order and then wants to close the Queue or 'Now Playing' he or she has to go all the way up to the Queue to close it.

**Solution**: The app should close the queue by tapping on the song's poster instead of pausing it.

**Comment by FOSS-Love** [comment]
Instead of removing the already existing feature, i have another solution.

Make the now playing header to stick at the top even when scrolling the queue, so when we tap on now playing it should drop down, same as the way it opens up when we touch on now playing. 

Don't know the technical possibility, but a theoritical solution.

**Comment by Sangwan5688** [comment]
Umm, I don't think I will make a fixed header coz it won't look that good. Anyway, I will do something so as to resolve the issue.

**Comment by hellyeahmfs** [comment]
@Sangwan5688 I think you should just replace the functionality of pausing with closing of the Queue. It would work fine.
