### ISSUE TITLE
Importing playlist 

### ISSUE THREAD

**Issue by Evil-Patrick** [Sangwan5688/BlackHole#116]
Describe the bug

So I was using spotify previously and I decided to import my playlist from spotify but when i imported my playlist some songs are missing or i think replaced by other song by same artist.

Screenshots

![Screenshot_2021-09-07-13-44-03-54.jpg](https://user-images.githubusercontent.com/37536130/132311065-f1e9ffeb-3131-4931-824c-03316d81e58c.jpg)

![Screenshot_2021-09-07-13-44-34-29.jpg](https://user-images.githubusercontent.com/37536130/132311083-157a58a4-b881-42a0-aa0f-9f59dad5929d.jpg)

Smartphone

 - Device: Realme 6
 - OS: Android 10
 - App Version v. 1.10.1

App Logs

I don't know how to do it

**Comment by Sangwan5688** [comment]
See, BlackHole uses JioSaavn to fetch songs. When you import any playlist from Spotify or YouTube, what BlackHole does is that it takes the song and artist name, then searches for that song on JioSaavn and adds the top search result.
Now, it might happen that there are no search results, so that song won't be added or it might happen that the song is not the top result but 2nd or 3rd result. So in that case some other song will be added, which is the top result.

Now there are some things to keep in mind.
First, if you are not from India then use VPN while importing. Coz if you don't use VPN then the search results will show random songs.
Second, make sure you have song language as per your songs. Let's say you have only selected Hindi and you are importing playlist with Punjabi Song. So it might happen that a Hindi song with same name come at top, not the Punjabi one.
Finally, it might happen that the song you are looking for isn't available on JioSaavn at all. So, in this case too, any other song may or may not appear at top, causing app to either skip that song or adding any other song which come at the top.

**Comment by Evil-Patrick** [comment]
What if that song is not available on jiosavaan is there still any fix for that?

**Comment by Sangwan5688** [comment]
Sadly, There's no fix for that now. One thing you can do is add it from YouTube but there are some issues with youtube songs added to playlist. Coz there's a time limit after that youtube song won't play with same link.

**Comment by Evil-Patrick** [comment]
Ok I hope you will fix this in future releases
