### ISSUE TITLE
Regarding cross-platform ambitions

### ISSUE THREAD

**Issue by vairag22** [Sangwan5688/BlackHole#159]
I've been following the development of this app closely, and of course using it for sometime now. So I wanted to seek some clarification regarding the future of this app.

BlackHole advertises itself to be cross-platform in foreseeable future. It's mentioned on the [website](https://sangwan5688.github.io/BlackHole/#download) and there's work being done, issue #42. So I assume distribution has been figured out? iOS does not officially allow sideloading, though EU is pressuring Apple but given the current state of affairs that might never happen. There are unofficial solutions but how secure and functional they are I do not know. [Here's link to the report that Apple submitted to EU.](https://www.apple.com/privacy/docs/Building_a_Trusted_Ecosystem_for_Millions_of_Apps.pdf)

Concerning desktop support , issue #74, I still don't understand why? Spotify, YouTube and JioSaavn can be used ad-free with uBlock Origin and these websites are also installable as PWAs. There are several open-source downloaders available as well as high quality media players with years of polish.

So is there a specific reason to target any other platforms but Android?

**Comment by Sangwan5688** [comment]
Well, I made this app for myself initially and well that's how most of open source projects work. I personally don't care much about about iOS or Mac support coz I don't have them. I'm an android user and that's why I made the app for Android at first. Now coming over to desktop support. I understand that you can stream to other sources but I personally download a lot of songs on PC and then listen to them offline. I can download them from other websites and stuff, but you see you can do that on android too but still you download from BlackHole coz it's easy to download from it. Just one click and done. That's the reason why I have added the desktop support for this app. Also, in flutter you don't actually have to do too much extra work to create it for other platforms. It's pretty simple and easy, just write one code and create it for others. Only some edits are needed. I'm waiting for packages like `just_audio` and `audio_service` to support windows soon. They are working on that and with that done, it will be just a piece of cake it create BlackHole for windows.

**Comment by vairag22** [comment]
My point was that Android version should be given first-preference since there are plenty of useful features still on hold, if you wish to extend the app to desktop that's your choice. However, iOS version is a fruitless endeavor plus you were one to open that issue (#42).

**Comment by vairag22** [comment]
My point was that Android version should be given first-preference since there are plenty of useful features still on hold, if you wish to extend the app to desktop then it's your choice. However, iOS version is a fruitless endeavor plus you were one to open that issue (#42).

**Comment by vairag22** [comment]
My point was that Android version should be given top-priority as there many useful features are still pending (Cast, Android Auto support). If you wish to extend the app to desktop then it's your choice however iOS is a fruitless endeavor plus you were the one to open that issue (#42).

**Comment by Sangwan5688** [comment]
My priority is still Android. I created that issue just coz someone else can create the app for iOS side as code is already there. As of Windows, I haven't done anything special for windows yet and still waiting for some packages to support it.

**Comment by vairag22** [comment]
Nice. Didn't ask you earlier but do you mind if I implement this app via Kotlin? That's initially going to lock the app on Android however that's a non-issue because Android apps are supported on Windows 11 and certain Linux distros (Not targetting iOS and macOS). If I am successful then we can slowly phase this app to that codebase. Might solve some performance issues like the one you mentioned in issue #155.

**Comment by Sangwan5688** [comment]
Umm, well it's true that making it in kotlin will certainly increase it's performance. But I don't really want to lock it to just android. If you want to write kotlin code then, what you can do is write some native code for offline section. I can actually call any native function written in the android folder. And the offline section of app, really need a lot of improvement. If you want you can create that section in kotlin itself (not UI, just function like function to get all data like audio files, function to get all playlists, to get their artwork and all that). And as of now I don't have any plan to include that offline section on other platforms. So, it will really help a lot.
