### ISSUE TITLE
Title "now playing" scrolls up with the list

### ISSUE THREAD

**Issue by Avendo07** [Sangwan5688/BlackHole#160]
**Describe the bug**
The title of now playing card moves up with the list, ideally it should be pinned to the top of the list

**Expected behavior**
Now Playing header should stick to the top

**Screenshots**
- Current behaviour
![Screenshot_20211031_172843](https://user-images.githubusercontent.com/43928724/139582061-58fafa3d-1528-45b7-bebe-bd85bf99b656.png)
- Expected Behaviour
![Screenshot_20211031_172957](https://user-images.githubusercontent.com/43928724/139582084-d5f98e9f-8cdd-4655-94b0-b1adbc4a86de.png)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10
 - OS: Android 11 (Pixel Experience)
 - App Version v1.11.0

**Comment by Avendo07** [comment]
I can make the required changes if you approve of the change.

**Comment by Sangwan5688** [comment]
Umm, I will do it in next commit. It's nothing big actually, just have to move it to head. If you want to push a PR, I would suggest making some more changes. Like you can make it kind of draggable, so that it removes when user is at top of list and scrolls down. And you can add some shading or something like that so that it kind of look like they are moving behind that now playing. Plus you can add more improvements from your side in its design.
If you just want to create this particular change, then I would say rather skip it coz it's just a 1-2 line change.

**Comment by Avendo07** [comment]
Yeah, I was thinking of making some more changes, just didn't know if I should add it in the same issue or not. I'll see what I can do and push a PR.
