### ISSUE TITLE
App freezes on hitting play.

### ISSUE THREAD

**Issue by Vishnu2jd** [Sangwan5688/BlackHole#174]
App freezes everytime I hit play on my oneplus 6 running lineageos. Everything other than playback seems to work . Maybe it was lineageos to blame, since on my other phone (redmi) running stock os works fine.

Device: Oneplus 6 running lineageos 18.1 (Android 11)

**Comment by Sangwan5688** [comment]
There an option "Use Equalizer" in (BlackHole) settings. Try turning that off. Some custom roms have issues with equalizer. Anyway, turn that off, restart app and then check. If issue still persists lemme know.

**Comment by Vishnu2jd** [comment]
Yep it works now. Thank you. I am genuinely impressed.

**Comment by Sangwan5688** [comment]
Ya, I will make the equalizer off by default in next version. So that no one face any issue.

**Comment by Sangwan5688** [comment]
I have turned off Equalizer by default in latest commit. So, no one will face the issue of songs not playing in future. If anyone want equalizer then they can turn in on from app settings if it's not causing any issue related to audio not playing (resulting in a transparent screen over UI instead of playscreen making it look like app is frozen)
