### ISSUE TITLE
German language support

### ISSUE THREAD

**Issue by paulhersch** [Sangwan5688/BlackHole#184]
I would like to add German language support. How can i get started on this?

**Comment by Sangwan5688** [comment]
You will have to translate the file [app_en.arb](https://github.com/Sangwan5688/BlackHole/blob/main/lib/localization/app_en.arb) present inside [localization](https://github.com/Sangwan5688/BlackHole/tree/main/lib/localization). Just create a new file there, according to your language code. For German, I think it's 'ge' or 'gr'. So just create a new file 'app_ge.arb' or 'app_gr.arb' whichever it is, with all text translated inside. You can refer to other translated file inside [localization](https://github.com/Sangwan5688/BlackHole/tree/main/lib/localization).

**Comment by mondlicht-und-sterne** [comment]
the whole thing would be easier if we could translate it at weblate, e.g. [hosted.weblate](https://hosted.weblate.org/) or [weblate.bubu](https://weblate.bubu1.eu/)

**Comment by Sangwan5688** [comment]
Actually, the thing is flutter need some other things to be done in the code side too. I will try to add a small code so that it can manage those things by itself. Apart from that weblate doesn't even support arb files afaik. Arb files are similar to json but still there can be formatting issues and all. The default way offered by flutter is bit complex compared to others.

**Comment by Sangwan5688** [comment]
Ok, finally. Here you go:
https://hosted.weblate.org/projects/blackhole/
