### ISSUE TITLE
No restriction for downloading same song multiple times

### ISSUE THREAD

**Issue by asifmhdashik** [Sangwan5688/BlackHole#19]
The offline songs are not denoted as offline in the player and music can be duplicated multiple times.

**Comment by Sangwan5688** [comment]
Unlike other apps where downloaded songs are stored inside the app directory and can't be accessed by other apps, BlackHole saves songs in the external storage. This means you can play those songs in other music player apps, share them offline, and all those stuff. Think of it the same way you download any song from a website. It's true that there's no restriction on download, you can download again but it will not create multiple entries. There will always be just one entry for one song (Multiple downloads just replace the old one). The restriction wasn't made so because if any user moves or deletes the song then he/she can download it again.
Although it is possible to scan the directory and check if it is present or not. But it will just make the whole process more time-consuming.
I am keeping this issue open for time being. If I got more requests or other valid reasons, I will think about implementing it.

**Comment by Sangwan5688** [comment]
I have added an alert dialog to as the user if he/she wants to an already downloaded song again or not.
