### ISSUE TITLE
Scoped storage instead of all files access permission

### ISSUE THREAD

**Issue by saturn279** [Sangwan5688/BlackHole#218]
**Is your feature request related to a problem? Please describe.**
Requires all files access permission for downloads. 

**Describe the solution you'd like**
Give access to specific folder/s, like in the screenshot below. 

**Describe alternatives you've considered**
Alternative solution could be downloading in sandboxed app folder inside ~android/data/org.blackhole which shouldn't require storage permissions (far as I know). 

**Additional context**
![Screenshot_2022-01-19-00-46-06-72_5734e8eb49b4234b62f913f831715b0f](https://user-images.githubusercontent.com/45988700/150003991-583fe00e-1e43-48a0-8152-e21fe78e6159.jpg)

**Comment by Sangwan5688** [comment]
See, I tried using scoped storage at first but there are some limitations. First, It's not allowing me to create new files without manage storage permission. It just allows the app to get file details. I can play them but can't create new files. That's the reason why it needs manage permission. If you don't wanna download anything then you can just turn that off, app will work fine. As for downloading inside app folder, I don't want to do so and I think 70-80% users dont want that. It's the sole reason for many users why they use blackhole instead of other apps i.e coz it lets you download in your external storage.

**Comment by saturn279** [comment]
I understand, it is a bit annoying when apps store media in the sandboxed folder (Telegram's new update), but it'd be nice to have that option if user declines storage permission.

User's who accept will have their files stored on an external folder and user's who decline will have them in the internal one. 

Anyways, thoroughly enjoying your app, keep up the good work. 

![Screenshot_2022-01-19-15-29-19-65_ab1359306de43320f9557c797b1c4be5](https://user-images.githubusercontent.com/45988700/150110013-f1936db1-df32-4a54-a7a7-d1b910a57c61.jpg)

**Comment by Sangwan5688** [comment]
Nah, I don't actually have any plan to do so. I would keep if just external one. And ya, I do understand your concern a bit that it's scary at first when an app asks to manage your whole external storage but I can't do anything, blame android for that. Anyway, If you have any concern regarding privacy or security you can go through whole source code. It's right there for you :)

**Comment by saturn279** [comment]
Fair enough, truly appreciate your work.
