### ISSUE TITLE
Downlaoded song is not of 'download quality' in settings.

### ISSUE THREAD

**Issue by Agitated-Junk** [Sangwan5688/BlackHole#23]
Songs are getting downloaded at streaming quality no matter what you've set as 'download quality'. In order to download the song at 320kbps I've to keep the streaming quality as 320kpbs.

**Comment by Sangwan5688** [comment]
I don't think it's the case. How did you confirm the fact?

**Comment by Agitated-Junk** [comment]
Well, I tried it with different combination like keeping download quality same and changing the streaming quality and every time I downloaded the song by changing streaming quality, size of it also changed. I confirmed the bitrate from my other music app as well.

**Comment by Sangwan5688** [comment]
I tried it but there's no such issue for me. I even checked the code and everything is fine with the code too. And I really don't think there's such an issue. So please check once again and make sure that you are changing streaming quality and not download quality. Also, if you download the same song again, it replaces the old one. So make sure to refresh your file manager after downloading so that it checks for the latest file.
If the issue still exists and is reproducible, please provide more details like steps to reproduce the issue, screenshots, etc. I will look deeper then.

**Comment by Agitated-Junk** [comment]
**Intention**: To download songs at 320kbps and stream at 160kbps.
**Steps** 
1. Keep your download setting as 320kbps
2. Keep streaming setting at 160kbps.
3. Search for the song and download it.
4. Check the bitrate of downloaded song.
**Expected result**: Song downloaded is of 320kbps bitrate.
**Actual result**: Downloaded song is of 160kbps bitrate and not 320kbps.
Example: [Here](https://imgur.com/a/BjPjuXc)

P.S. 
1. Streaming quality at 96kbps and 320kbps is not affecting the download. Only 160kbps is affecting it.
2. I've only checked it with 320kbps as download setting.

**Comment by Sangwan5688** [comment]
Thanks for the details. I will look into that
