### ISSUE TITLE
Add shortcuts to the Home page

### ISSUE THREAD

**Issue by ghost** [Sangwan5688/BlackHole#236]
**Is your feature request related to a problem? Please describe.**
Not a problem but I find it annoying that I have to go through multiple menus to get to my downloads and playlists. It kind of throws me off when I quickly want to change the song to something specific or change which playlist is playing.

**Describe the solution you'd like**
Add shortcuts to the home page to certain places like Downloads or Playlists. Preferably customisable like choosing which shortcuts show up or which playlist the button opens to. Maybe also a shortcut to liked songs.

**Additional context**
iPad (Same for desktop apps) and phone screenshots provided: (Editing skills aren't that good 😅)
![Blackhole IPad SS](https://user-images.githubusercontent.com/83172580/151749231-2a386636-0e01-4b93-be70-041afbef8cbb.PNG)
![Blackhole Phone SS](https://user-images.githubusercontent.com/83172580/151749235-920360a6-d554-42ca-b8d8-079ff0e2f52d.png)

**Comment by Sangwan5688** [comment]
Umm, It does sound good but technically it will just save you 1 click, that's all. It would be a different case if they were too deep inside app, but I don't think that's the case. Plus, I think downloads and playlists are even in navigation drawer. I'm planning to keep it the navigation drawer open in rotated view, so that might save you 1 click on ipad. Anyways, I will think about 1 or 2 buttons. But adding everything won't be possible. Also, I do plan to add your playlists in last session thing. Last session will then show as a single image followed by your playlists and local music. I hope that will also solve your problem upto some extend.

**Comment by CommanderEntropy** [comment]
Yes, I think adding playlists to"Last Session" will be a good idea. Maybe a way to pin them to the home page can be added? Since I do change playlists sometimes and it can get pushed back. Pinning them will make sure I find it in the same place every time. 
Adding all of the icons may make it too crowded on some devices, so 1 or 2 icons should be fine. It'll just make it a bit more obvious as to where downloads and playlists are located.

**Comment by Sangwan5688** [comment]
Closing this, as playlists now show on home screen
