### ISSUE TITLE
Can i fetch songs from another source?

### ISSUE THREAD

**Issue by ogbodotg** [Sangwan5688/BlackHole#24]
Hello, I came across your amazing music app yesterday and it has kept me busy since then.

One problem I have however is fetching some of my already existing songs in Firebase Firestore. 

I know this might probably not be a part of your project, but i would really appreciate if you could guide me on how to source my private music files directly from firestore collections.

**Comment by Sangwan5688** [comment]
There's no such option right now to fetch your own songs from firebase. And I don't think I will ever add it as it's not needed. I might add an option to upload playlists and fetch them, but those songs will be from the app itself. If you are familiar with flutter, you can make changes in the code itself and build your own app from the code.

**Comment by asifmhdashik** [comment]
Can you add YouTube as library so that it would give wide variety of search results and enable downloading podcasts too. Videos can converted seamlessly with fmpeg

**Comment by Sangwan5688** [comment]
@asifmhdashik I have tried that earlier, way before I started working on this app. The music download feature was available on just the command line back then. The thing is it takes a lot of time to convert the video (not so much but quite comparable with the current method). I have tried other platforms too, websites like mr-jaat.com, djpunjab, songspk, etc. I have tried all, way back, and believe me this was the best method I could found. That's why I implemented it inside the app. It's not that I don't want to improve more. I do have some plans of adding other platforms like youtube but not like this way. I will provide a feature to search any song on youtube if it's not in current search results. I won't convert it to mp3 but let the user play the whole video inside the app. I will implement this feature while playing any song too so that If users want to watch the video then they can watch it while playing song (something just like youtube music although it won't be that much great)
