### ISSUE TITLE
Pre loaders are slow and loader is in blue color

### ISSUE THREAD

**Issue by asifmhdashik** [Sangwan5688/BlackHole#26]
The pre loader for the trending in the home is slow and is left empty at launch with just the search bar and last session. And also the loader is not changing according to the theme. 
![Screenshot_20210521_201107_com shadow blackhole](https://user-images.githubusercontent.com/76432849/119156093-84fa5080-ba71-11eb-9b1b-0111120f87f3.jpg)
![Screenshot_20210521_201125_com shadow blackhole](https://user-images.githubusercontent.com/76432849/119156100-86c41400-ba71-11eb-8511-889a9ecc4ed7.jpg)

**Comment by Sangwan5688** [comment]
I will think about caching the playlists so that they will less time.
Now coming over to the loader, the loader color changes with a change in theme. I'm not encountering the issue. Is the issue only with loader in top Spotify Songs? Anyway, I will add code to change the color with a change in theme. That should solve the issue whatever be the reason.

**Comment by NeutralDevop** [comment]
@Sangwan5688 Can you try delaying the splash screen till firebase is initialised .

**Comment by Sangwan5688** [comment]
@NeutralDevop No, I don't wanna do it. The best choice right now would be to cache the playlists from the last session and show them until the new one's load.

**Comment by Sangwan5688** [comment]
I have added cache support for the home screen playlists as per music language. It should be much faster now. Lemme know if you face any issue.
