### ISSUE TITLE
App stuck 

### ISSUE THREAD

**Issue by brnwlshubh** [Sangwan5688/BlackHole#30]
**Describe the bug**
App stuck sometimes(first time if not opened in recent apps) when offline content loads.

**To Reproduce**
1. Go to 'Library'
2. Click on 'My Music'
3. Swap/slide to other options

**Expected behavior**
While loading offline content it is not responding for other option.

**Smartphone (please complete the following information):**
 - Device: [Samsung J7 Prime]
 - OS: [ Android 8]
 - App Version [v1.6]

**Comment by Sangwan5688** [comment]
Most probably because of too much processing while loading songs. I will try to add an option to select folders to search for music. This will significantly reduce processing time.

**Comment by Sangwan5688** [comment]
The issue was because of Spotify Top charts. As the app used to scrap data from web. Too much processing was causing the app to stuck for 1-2 second. When user directly moves to library, still app loads top charts as it moves form one homepage to top charts then to library. And when user clicks on my my music, further processing of local music takes place causing app to stuck. The issue was resolved with latest commit cb4707d and app version v1.7 where different isolate is created for web scrapping.
