### ISSUE TITLE
When no languages are selected in settings, the trending is null

### ISSUE THREAD

**Issue by asifmhdashik** [Sangwan5688/BlackHole#32]
**Describe the bug**
When none of the languages are selected, the trending screen is not showing the default lang.

**Comment by Sangwan5688** [comment]
By default, "Hindi" is set as the default language for trending songs. If a user removes it from settings, that means he/she doesn't want to see songs of "Hindi". I can't forcefully show the user "Hindi" songs if he doesn't select any other language. If the user doesn't select any other language then it just means he/she doesn't want to see any trending songs at all. This is an intensional behavior, not any bug. If you meant something else lemme know otherwise, the issue can be closed.

**Comment by asifmhdashik** [comment]
I meant this only. You can close the issue.
