### ISSUE TITLE
Result not found if I select a song.

### ISSUE THREAD

**Issue by SzeligBalazs** [Sangwan5688/BlackHole#339]
**Cannot listen to songs, because of an error**
If I choose a song I get an error with this error message: SORRY, Results not found. Then I also get a popup error message:

```
Error: type '_OneByteString' is not a subtype of type 'List<dynamic>' in type cast
```

**To Reproduce this error**
Steps to reproduce the behaviour:
1. Open the app.
2. Click on any song or album.
3. And then the error will pop up.

**Screenshots**
Here is a screenshot.

<img src="https://user-images.githubusercontent.com/80389103/173030253-008adc06-9daf-411d-be15-de0b2e32d17b.jpeg" alt="Screenshot" width="200px"/>

**Device Details:**
 - OS: Android
 - Version: 11
 - Device: Redmi 9
 - App Version v1.14.0

**I use the app in the *English* language and the Spotify charts location is *Hungary*.**

Thanks in advance,
SzeligBalazs

**Comment by satyyam11** [comment]
**This happened with me too**

**Comment by BrightDV** [comment]
This app uses JioSaavn to provide you the songs. However, you have to be in India to access all the songs, otherwise you will get only Indian songs or no songs at all, like in your case. The only workaround is to use a VPN or the in-app proxy with an indian server. See [this issue](https://github.com/Sangwan5688/BlackHole/issues/52) for more.

**Comment by SzeligBalazs** [comment]
Thank you @BrightDV!
