### ISSUE TITLE
Cant find songs in english language

### ISSUE THREAD

**Issue by JacobGarv** [Sangwan5688/BlackHole#52]
I have my language set to English, and my country set to united States. The Spotify top charts for local correctly display English speaking artists(Justin Bieber,  Lil nasX, Type, The creator, etc.) However when I press on them to play, it either says ''Sorry, results not found.'' Or it will display results from Hindi artists, for example when I tap on Bad Habits by Ed Sheeran, it comes up with Bad Habits by Navjeet, and Bad Habits by Dilraj.

I also dont get any results by searching for American artists such as Black Sabbath or Edward Sharpe and the magnetic zeroes.

Note: im using the precompiled arm64-v8a apk,  v1.8

**Comment by Surendrajat** [comment]
@JacobGarv BlueHole uses Ji0Saavn as the backend for music streaming, so even if you see the song in Spotify top charts, the songs may not be available on JioSaavn service. The latest beta version has YouTube backend supported if you want, though.

**Comment by Sangwan5688** [comment]
@JacobGarv As already explained by @Surendrajat BlackHole uses JioSaavn, whereas the Spotify top charts are scrapped from the Spotify Website. Spotify has a much larger database, so some songs might not be available on JioSaavn, which results in Empty Screen or songs from different artists. Although it's not like that there're not even trending songs like "Bad Habits". One user recently reported that he can't even find the common English Songs. And I'm not sure why, but for some reason, JioSaavn shows Indian Search results when you try to search from another Country. The issue can be resolved by using any VPN with an Indian Server. I will try to find a better solution in the future. Till then, it's the only workaround you can use.

**Comment by Sangwan5688** [comment]
Should be resolved up to some extent with d918ded

**Comment by Sangwan5688** [comment]
As in-app proxy is already added and nothing more can be done regarding the issue, I'm closing it with some final comments for everyone.

BlackHole uses JioSaavn API to get all song data, including search results. JioSaavn API for some reason provides Indian Search Results to everyone who tries to access the API outside India. The location is tracked using the IP Address, so nothing can be done about that. The only way is to use any `VPN` with an `Indian Server`. There's `in-app Proxy` support too, which can be used instead of VPN. But as the proxy is free, it might or might not work. You can check for better Indian Proxies and use them instead of the default one in case the default one isn't working fine. You need `not` use VPN all the time. It's needed just for "Search", "Spotify Import" and "Spotify Top Charts" as all three depend upon search results.
If you don't want to use VPN or in-app proxy you can use the `YouTube Section` to get the songs you are looking for. Although the Quality of the YouTube section isn't that high as JioSaavn still, can be used as a Backup. YouTube Section will be improved more in the future.

**Comment by vehosah** [comment]
Nobody would want to download a live video dressed as a Mp3

**Comment by vehosah** [comment]
Then add more sources, like vk,chiasenhac,soulseek, deezer, netease

**Comment by vehosah** [comment]
> @JacobGarv BlueHole uses Ji0Saavn as the backend for music streaming, so even if you see the song in Spotify top charts, the songs may not be available on JioSaavn service. The latest beta version has YouTube backend supported if you want, though.

If I was desperate about it

**Comment by Sangwan5688** [comment]
@vehosah I understand that no one wants a video dressed as Mp3 but that's the only thing I can do as of now. Adding other sources like that ones which you suggested isn't possible for me. It's not like I can add every music source out there. Also, please create a single comment if possible. Adding 3-4 comments like this won't do any good to any of us.

**Comment by Coderdude112** [comment]
@Surendrajat You said that YouTube backend was supported in the "latest beta version". Was this referring to the YT section in the bottom nav bar or the YT backend for search? Also, what beta version if you don't mind me asking.

---

@Sangwan5688  Not sure how you are doing calls to JioSaavn and not sure if it would provide the same quality, but would it be possible to use [NewPipe Extractor](https://github.com/TeamNewPipe/NewPipeExtractor) to get the same data JioSaavn provides?

**Comment by Sangwan5688** [comment]
@Coderdude112 newpipe extractor is used in youtube section of the app (which can be accessed from the youtube section in bottom nav bar). So, if jiosaavn section (home section) doesn't have the songs that you want then you can use youtube section instead. There are few things which need improvement in yt section, and I'm slowly doing so.
