### ISSUE TITLE
App is not opening past the splash screen

### ISSUE THREAD

**Issue by Akshay2595** [Sangwan5688/BlackHole#6]
![Screenshot_2021-05-03-09-51-48-08_a2df05e64545de9e48d383611b669e6e](https://user-images.githubusercontent.com/29795875/116841004-6e40a680-abf5-11eb-8846-3df62b9bf513.jpg)

App is stuck on the splash screen, not working further. I'm using v1.3

**Comment by Sangwan5688** [comment]
Can you try with v1.4. There was some issue in v1.3. Lemme know if you still face the issue in v1.4

**Comment by Akshay2595** [comment]
I just updated the app to v1.4, still facing the same issue :(

**Comment by Sangwan5688** [comment]
Which device are you using? and Android Version?

**Comment by Akshay2595** [comment]
I'm using realme 3 pro, running on android 10. Btw v1.0 was working fine.

**Comment by naqushab** [comment]
Same issue is happening to me as well.

**Comment by Sangwan5688** [comment]
Ok, I will check. You can use the earlier version till then.

**Comment by Sangwan5688** [comment]
As I'm unable to reproduce the error, I have a few questions.
1. Were you able to launch the app even once?
2. Does it happen every time you open the app?
3. Does clearing app data (storage data not just cache) solves the issue?

**Comment by Akshay2595** [comment]
1) App gets launched everytime but it is just stuck on the splash screen, seems like some process is not being done there..

2)yes, it's happening everytime. Like I said it was working fine when I first downloaded and installed apk, I started facing this issue after sometimes ones I updated to v1.2

3) clearing cache is not helping either!

4) I haven't tried on other device, I'll try it on my sis's phone tomorrow.

Also I'll try the armeabi apk.

**Comment by Akshay2595** [comment]
Hey Ankit,

I just tried the armeabi-v7a apk, and it's working fine on my device. Sorry for wasting your time on this, I should've tried this before raising the bug, really sorry. I'm closing this issue

**Comment by Sangwan5688** [comment]
It's fine.
I'm thinking to release Fat APK from next time on as the main apk file so that anyone won't have this problem. But it will be of larger size. So, I suggest anyone who's reading this, download Fat APK if you don't know about your device architecture. I will also release arm64-v8a and armeabi-v7a. So if you are sure about your device architecture and don't want to waste data on Fat APK then you can even download those. As for now, I have made a release containing all APK files.
From v1.5 onward in-app update options will also be changed accordingly.
Any other suggestions are welcomed.

**Comment by naqushab** [comment]
Yes, I needed the 64-v8a version of app. It works fine now. Thanks @Akshay2595!
