### ISSUE TITLE
Cannot debug/test application...

### ISSUE THREAD

**Issue by cristo1985** [Sangwan5688/BlackHole#69]
Hi,
i've followe all steps but cannot make it work. How can i do solve it?
The error is in picture:
<img width="788" alt="Schermata 2021-07-14 alle 15 12 51" src="https://user-images.githubusercontent.com/13002905/125628252-3c340b27-4307-4807-b6eb-557a4f5ff84e.png">
Thanks very much!
Cristian

**Comment by Sangwan5688** [comment]
Looks like your Gradle wrapper is missing. Please make sure you have android SDK and all that stuff that is necessary for building an app. You can run `flutter doctor` to check if everything is installed or not

**Comment by Sangwan5688** [comment]
You can check more details on how to install and all on [flutter website](https://flutter.dev/docs/get-started/install/macos)

**Comment by cristo1985** [comment]
> Looks like your Gradle wrapper is missing. Please make sure you have android SDK and all that stuff that is necessary for building an app. You can run `flutter doctor` to check if everything is installed or not

Hi, executed the doctor:
![image](https://user-images.githubusercontent.com/13002905/125634862-8f30a328-3631-47be-b8a2-d1212b6a4cdd.png)
It's all ok!

**Comment by Sangwan5688** [comment]
1. Delete the flutter cache (<installation folder>/bin/cache);
2. Delete gradlew and gradlew.bat in android folder (and in some cases android/gradle/wrapper/gradle-wrapper.jar too);
3. Run flutter run again.
If you still encounter the issue then try searching online on StackOverflow or somewhere else. As the problem is not related to the project.
