### ISSUE TITLE
Unable to stream any song from this particular album

### ISSUE THREAD

**Issue by onlytanmoy** [Sangwan5688/BlackHole#77]
First things first, many thanks for this amazing app 💯 
I just faced this weird issue specifically with this album. Please see screenshot below.
![Screenshot_20210717-090656](https://user-images.githubusercontent.com/48493659/126030713-59168c7b-3906-4867-a88b-074c50c3772a.jpg)
Whenever I tap on any of the songs in this album, I get this white overlay and nothing happens 🤷‍♂️
![Screenshot_20210717-090703](https://user-images.githubusercontent.com/48493659/126030757-0e40c110-a291-428d-bb03-1f8f0579a2d6.jpg)
I can download the song though only that it won't stream and I am more into the later :)
Not sure why this is happening with this specific album only, any idea mate?

**Comment by Sangwan5688** [comment]
Looks like there's some error there. I will check later and will let you know.

**Comment by Sangwan5688** [comment]
Well, it is working fine for me. Maybe there's some issue which I'm not able to reproduce. Is this happening every time for you?? If you are a developer and know how to get app logs, then can you do so? It would really help me to solve the issue, as I can't reproduce it. Also, make sure you are using the latest version.

**Comment by onlytanmoy** [comment]
Yeah happening every time for me, tried in a different android set and also via emulator in my laptop, exact same behaviour as given in the screenshot earlier. Sorry not aware how to get app logs. I am on the latest version.

**Comment by Sangwan5688** [comment]
Ok, the issue was because of `Duration`. The duration of the song is either `null` or `zero`. Coz of that it was causing an error which was shown as the white overlay. I'm not sure when I fixed it but it is working properly for me. If you are on the telegram group then you can try the beta version and then lemme know. So that the issue can be closed.

**Comment by onlytanmoy** [comment]
Ok, so I tried the beta version of the app from TG group now.
The songs from that album are playing now, no white overlay. But the duration of the song is shown as 00:00 and you cannot forward seek the song.

**Comment by Sangwan5688** [comment]
Ya, that's because there's no duration in the API response for that song. I might add an option to use the player to get its duration after the song has been loaded but it will cause some lag. It's very rare to have a song without duration and I think having it like that is much better. Or I can add a fake duration like let's say 3 minutes for any song without duration. That way you will be able to use the slider but the duration will be fake so it might skip to next before 3 minutes or will keep playing even after the slider has reached its max value i.e. 3 minutes.

**Comment by onlytanmoy** [comment]
Hmm..ok..got you mate, no need to take the hassle of adding the fake duration, the songs are streaming and I am happy with that 😀 I will put this ticket to rest now. Have a nice day ahead.
