### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by saikrishna7149** [Sangwan5688/BlackHole#804]
**Describe the bug**
Tried downloading a bunch of songs from jio saavn playlist and download is not at all started even after 10 minutes.

**Steps To Reproduce**
1. Import jio saavn playlist 
2. Click on download all button

**Expected behavior**
All the songs from the playlist should be downloaded for offline use.

**Screenshots**
If applicable, add screenshots to help explain your problem.![Screenshot_20240202_000043.jpg](https://github.com/Sangwan5688/BlackHole/assets/45508202/2d9f36e4-da7b-4493-ba98-18e0e2faa8f6)

**Device Details (please complete the following information):**
 - OS:  Android
 - Version: Android 13
 - Device: samsung s20fe 5g 
 - App Version 1.15.0

**Comment by Shentia** [comment]
same for iOS

**Comment by Sangwan5688** [comment]
There was an issue with import in previous version. The playlist which you are trying to download has `Unknown` artist, which shouldn't be the case for JioSaavn imported playlists. So, this playlist never got imported correctly. Just update to the latest version and import it again.
As for ios, there was an issue with metadata editing due to which the download used to get stuck at 100%, that's also fixed in beta versions, but as there's no beta version for ios, you won't be able to test it

**Comment by saikrishna7149** [comment]
Which is the latest version 1.15.?
