### ISSUE TITLE
Downloaded songs don't display in library

### ISSUE THREAD

**Issue by shazgames** [Sangwan5688/BlackHole#81]
**Describe the bug**
Downloads doesn't show any downloaded songs.

**To Reproduce**
1. Go to YouTube tab and open any song
2. Click on 'Download' button
3. Wait for complete download
4. Go to Library -> Downloads.
5. It's empty

**Expected behavior**
See downloaded songs in library.

**Smartphone:**
 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Android 11
 - App Version v1.9.0

**Comment by Sangwan5688** [comment]
The youtube section is still in beta and needs more improvements. As far as the download option is concered youtube provides the audio in `weba` format which can't be accessed by BlackHole. You can try playing it on any other player which supports weba format. I do have plans to convert `weba` to `mp3`. I will do so in future updates (I tried using ffmpeg but it increased the app size a lot will try something else). Also, I personally prefer and suggest downloading from the main section instead of the youtube one. YouTube part is just a backup in case you can't find your song in the main section. The max quality you can get from YouTube is 140 kbps weba which is nowhere near the 320 kbps m4a which you get from the main section.
